CREATE TABLE FW_ROLE_TASK
(
  ROLECD  CHAR(32 BYTE)                          NOT NULL,
  TASKID  CHAR(128 BYTE)                          NOT NULL
);

CREATE UNIQUE INDEX PK_FW_ROLE_TASK_ROLECD_ETC ON FW_ROLE_TASK
(ROLECD, TASKID);

CREATE TABLE FW_MENU_INFO
(
  MENUCD     CHAR(6 BYTE)                       NOT NULL,
  MENUNM     VARCHAR2(32 BYTE),
  MENUDEPTH  NUMBER(4),
  MENUSEQ    NUMBER(4),
  PARENTCD   CHAR(6 BYTE)
);

CREATE UNIQUE INDEX PK_FW_MENU_INFO_MENUCD ON FW_MENU_INFO
(MENUCD);


CREATE TABLE FW_MENU_TASK
(
  MENUCD   CHAR(6 BYTE)                         NOT NULL,
  TASKID   CHAR(128 BYTE)                         NOT NULL,
  TASKSEQ  NUMBER(4)
);

CREATE UNIQUE INDEX PK_FW_MENU_TASK_MENUCD_ETC ON FW_MENU_TASK
(MENUCD, TASKID);



CREATE TABLE M_MENU_MEMBER
(
  MEMBERID  VARCHAR2(32 BYTE),
  MENUID    VARCHAR2(32 BYTE)
);


CREATE TABLE U_MENUINFO
(
  ID            VARCHAR2(20 BYTE),
  NAME          VARCHAR2(32 BYTE),
  TEXT_KOR      NVARCHAR2(32),
  TEXT_ENG      VARCHAR2(32 BYTE),
  TEXT_OTH      NVARCHAR2(32),
  INPUTNAME     VARCHAR2(32 BYTE),
  OUTPUTURL     VARCHAR2(256 BYTE),
  REPORTPAGEID  VARCHAR2(64 BYTE),
  OUTPUTWIDTH   NUMBER,
  OUTPUTHEIGHT  NUMBER,
  VIEWCHECK     CHAR(1 BYTE),
  ICONINDEX     NUMBER,
  MENUSORT      NUMBER                          DEFAULT 0,
  AACC_F        NUMBER,
  ICM_F         NUMBER,
  UIP_F         NUMBER,
  CUST_F        NUMBER                          DEFAULT 0                     NOT NULL
);

CREATE UNIQUE INDEX U_MENUINFO_PK ON U_MENUINFO
(ID);


ALTER TABLE U_MENUINFO ADD (
  CONSTRAINT U_MENUINFO_PK
  PRIMARY KEY
  (ID)
  USING INDEX U_MENUINFO_PK);



